## DM
[dm_sub10]
raw_data_dirs = [
    "data/processed/dm_sub10",
]
raw_data_frags = [
    "",
]
combs = [
    [ ["rna", "adt"] ],
]
comb_ratios = [ 
    [ 1 ],
]
s_joint = [
    [ 0 ], 
]
train_ratio = 1
N = 256


[dm_sub20]
raw_data_dirs = [
    "data/processed/dm_sub20",
]
raw_data_frags = [
    "",
]
combs = [
    [ ["rna", "adt"] ],
]
comb_ratios = [
    [ 1 ],
]
s_joint = [
    [ 0 ],
]
train_ratio = 1
N = 256


[dm_sub50]
raw_data_dirs = [
    "data/processed/dm_sub50",
]
raw_data_frags = [
    "",
]
combs = [
    [ ["rna", "adt"] ],
]
comb_ratios = [
    [ 1 ],
]
s_joint = [
    [ 0 ],
]
train_ratio = 1
N = 256


[dm_sub100]
raw_data_dirs = [
    "data/processed/dm_sub100",
]
raw_data_frags = [
    "",
]
combs = [
    [ ["rna", "adt"] ],
]
comb_ratios = [
    [ 1 ],
]
s_joint = [
    [ 0 ],
]
train_ratio = 1
N = 256


# SLN
[sln_sub10]
raw_data_dirs = [
    "data/processed/sln_sub10",
]
raw_data_frags = [
    "",
]
combs = [
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
]
comb_ratios = [
    [ 1 ], [ 1 ], [ 1 ], [ 1 ],
]
s_joint = [
    [ 0 ], [ 1 ], [ 2 ], [ 3 ]
]
train_ratio = 1
N = 256


[sln_sub20]
raw_data_dirs = [
    "data/processed/sln_sub20",
]
raw_data_frags = [
    "",
]
combs = [
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
]
comb_ratios = [
    [ 1 ], [ 1 ], [ 1 ], [ 1 ],
]
s_joint = [
    [ 0 ], [ 1 ], [ 2 ], [ 3 ]
]
train_ratio = 1
N = 256


[sln_sub50]
raw_data_dirs = [
    "data/processed/sln_sub50",
]
raw_data_frags = [
    "",
]
combs = [
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
]
comb_ratios = [
    [ 1 ], [ 1 ], [ 1 ], [ 1 ],
]
s_joint = [
    [ 0 ], [ 1 ], [ 2 ], [ 3 ]
]
train_ratio = 1
N = 256


[sln_sub100]
raw_data_dirs = [
    "data/processed/sln_sub100",
]
raw_data_frags = [
    "",
]
combs = [
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
]
comb_ratios = [
    [ 1 ], [ 1 ], [ 1 ], [ 1 ],
]
s_joint = [
    [ 0 ], [ 1 ], [ 2 ], [ 3 ]
]
train_ratio = 1
N = 256


# bmmc
[bmmc_sub10]
raw_data_dirs = [
    "data/processed/bmmc_sub10",
]
raw_data_frags = [
    "",
]
combs = [
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
]
comb_ratios = [
    [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ],
]
s_joint = [
    [ 0 ], [ 1 ], [ 2 ], [ 3 ], [ 4 ], [ 5 ], [ 6 ], [ 7 ], [ 8 ], [ 9 ], [ 10 ], [ 11 ]
]
train_ratio = 1
N = 256


[bmmc_sub20]
raw_data_dirs = [
    "data/processed/bmmc_sub20",
]
raw_data_frags = [
    "",
]
combs = [
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
]
comb_ratios = [
    [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ],
]
s_joint = [
    [ 0 ], [ 1 ], [ 2 ], [ 3 ], [ 4 ], [ 5 ], [ 6 ], [ 7 ], [ 8 ], [ 9 ], [ 10 ], [ 11 ]
]
train_ratio = 1
N = 256


[bmmc_sub50]
raw_data_dirs = [
    "data/processed/bmmc_sub50",
]
raw_data_frags = [
    "",
]
combs = [
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
]
comb_ratios = [
    [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ],
]
s_joint = [
    [ 0 ], [ 1 ], [ 2 ], [ 3 ], [ 4 ], [ 5 ], [ 6 ], [ 7 ], [ 8 ], [ 9 ], [ 10 ], [ 11 ]
]
train_ratio = 1
N = 256


[bmmc_sub100]
raw_data_dirs = [
    "data/processed/bmmc_sub100_l2",
]
raw_data_frags = [
    "",
]
combs = [
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
]
comb_ratios = [
    [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ],
]
s_joint = [
    [ 0 ], [ 1 ], [ 2 ], [ 3 ], [ 4 ], [ 5 ], [ 6 ], [ 7 ], [ 8 ], [ 9 ], [ 10 ], [ 11 ]
]
train_ratio = 1
N = 256


#imc_ref
[imc_ref]
raw_data_dirs = [
    "data/processed/imc_ref",
]
raw_data_frags = [
    "",
]
combs = [
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
    [ ["rna", "adt"] ],
]
comb_ratios = [
    [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ], [ 1 ]
]
s_joint = [
    [ 0 ], [ 1 ], [ 2 ], [ 3 ], [ 4 ], [ 5 ], [ 6 ], [ 7 ], [ 8 ], [ 9 ], [ 10 ], [ 11 ], [ 12 ]
]
train_ratio = 1
N = 256
